rvm:
- 1.9.3
- 2.0.0
gemfile: Gemfile.ci
before_script:
  - psql -c 'create database cmsimple_test' -U postgres
  - 'cp spec/rails_app/config/database.travis.yml spec/rails_app/config/database.yml'
  - bundle exec rake db:migrate
  - 'sh -e /etc/init.d/xvfb start'
env:
  - DISPLAY=':99.0' CUCUMBER_OPTS='-f progress' CI_WAIT_TIME=10
script: bundle exec rake --trace
notifications:
  email:
    - cmsimple@modeset.com

