rvm:
  - 1.9.3
  - 2.0.0
env:
  - DISPLAY=':99.0' CUCUMBER_OPTS='-f progress' CI_WAIT_TIME=10
gemfile:
  - Gemfile.nolock
  - Gemfile
before_script:
  - sh -e /etc/init.d/xvfb start
  - cp spec/rails_app/config/database.example.yml spec/rails_app/config/database.yml
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:migrate
notifications:
  email:
    - cmsimple@modeset.com
script: bundle exec rake --trace
